### ISSUE TITLE
Tarea: Infografía sistemas numéricos, 24620171, Fidel Jiménez S.

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/infografia-Fidel20-01#1]
![Infografia Sistemas Numericos.png](https://github.com/user-attachments/assets/45102ad5-2b9c-4d72-99d8-4ff6c49300be)

![Infografia Sistemas Numericos.pdf](https://github.com/user-attachments/files/16735321/Infografia.Sistemas.Numericos.pdf)

**Comment by josealfredo79** [comment]
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:12/14
Referencias:13/14
Presentación:13/14
Calificación Final: 19/2
